# Generated by Django 2.2.8 on 2020-07-26 11:39

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('jsondata', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storage',
            name='data',
            field=jsonfield.fields.JSONField(blank=True),
        ),
        migrations.AlterField(
            model_name='storage',
            name='storage_id',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
