# Generated by Django 2.2.8 on 2020-08-04 12:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jsondata', '0002_auto_20200726_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storage',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creator', to=settings.AUTH_USER_MODEL),
        ),
    ]
