# Generated by Django 2.2.8 on 2020-08-04 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jsondata', '0003_auto_20200804_1450'),
    ]

    operations = [
        migrations.AddField(
            model_name='storage',
            name='url',
            field=models.CharField(default='', max_length=255),
        ),
    ]
