# Generated by Django 2.2.8 on 2020-08-10 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jsondata', '0006_auto_20200808_0451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storage',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project', to='jsondata.Project'),
        ),
    ]
