# Generated by Django 2.2.8 on 2020-08-11 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jsondata', '0007_auto_20200810_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(default='Untitled', max_length=255),
        ),
    ]
