# Generated by Django 2.2.8 on 2020-07-26 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='creator_id',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
