# Generated by Django 2.2.8 on 2020-08-10 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_creator_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='creator_id',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
